# Generated by Django 5.0.1 on 2024-02-19 16:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopApp', '0004_alter_brand_options_brand_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_delivered_time', models.DateTimeField()),
                ('order_delivered_status', models.CharField(choices=[('Assembling', 'Assembling'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Error', 'Error')], default=0)),
                ('product', models.ManyToManyField(to='orders.orderelement')),
            ],
        ),
    ]
